Repository honeycombio/example-greeting-service, pull requests merged in 2022-05, with the labels that each got.

#117 Update python dependencies, move to E&S
  python/frontend/frontend/__main__.py
  python/frontend/poetry.lock
  python/frontend/pyproject.toml
  python/message-service/message_service/__main__.py
  python/message-service/poetry.lock
  python/message-service/pyproject.toml
  python/name-service/name_service/__init__.py
  python/name-service/poetry.lock
  python/name-service/pyproject.toml
  python/year-service/poetry.lock
  python/year-service/pyproject.toml
  python/year-service/yearservice/yearapp/apps.py
Labels: type: maintenance, version: no bump, merge at will

#118 Small node updates while onboarding
  .tool-versions
  DEVELOPING.md
  Tiltfile
  node/README.md
  node/frontend/package-lock.json
  node/frontend/package.json
  node/message-service/package-lock.json
  node/message-service/package.json
  node/name-service/package-lock.json
  node/name-service/package.json
  node/year-service/package-lock.json
Labels: merge at will

#126 Parameterize which language or services run with Tilt
  .gitignore
  .tool-versions
  README.md
  Tiltfile
  node/.gitignore
Labels: status: review needed, merge at will
