Repository honeycombio/example-greeting-service, pull requests merged in 2022-11, with the labels that each got.

#256 [dotnet] add otel logs for year service
  dotnet/year-service/Program.cs
  dotnet/year-service/year-service.csproj
Labels: status: oncall

#264 feat: add @honeycomb/opentelemetry-node to frontend node service
  node/frontend/package-lock.json
  node/frontend/package.json
  node/frontend/tracing.js
Labels: type: maintenance

#276 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump
