Repository honeycombio/example-greeting-service, pull requests merged in 2023-03, with the labels that each got.

#448 maint: update asdf tool version declarations
  .tool-versions
  elixir/.tool-versions
  node/.tool-versions
  python/.tool-versions
  python/frontend/Dockerfile
  python/message-service/Dockerfile
  python/name-service/Dockerfile
  python/year-service/Dockerfile
Labels: type: maintenance, javascript, python

#395 maint: update go services
  golang/go.mod
  golang/go.sum
  golang/year-service/main.go
Labels: type: enhancement

#496 chore: fix up elixir example
  elixir/.tool-versions
  elixir/frontend/mix.lock
Labels: type: maintenance, merge at will

#508 maint: whitespace changes for dependabot
  .github/dependabot.yml
Labels: type: maintenance

#536 maint: elixir updates
  README.md
  elixir/README.md
  elixir/docker-compose.yml
  elixir/frontend/Dockerfile
  elixir/frontend/lib/frontend.ex
  elixir/frontend/mix.exs
  elixir/frontend/mix.lock
  elixir/message/Dockerfile
  elixir/message/config/runtime.exs
  elixir/message/lib/message.ex
  elixir/message/lib/message/application.ex
  elixir/message/mix.exs
  elixir/message/mix.lock
  elixir/name/Dockerfile
  elixir/year/Dockerfile
Labels: type: maintenance

#509 feat: update to use python distro
  Tiltfile
  python/frontend/frontend/__main__.py
  python/message-service/message_service/__main__.py
  python/name-service/.flaskenv
  python/name-service/Dockerfile
  python/name-service/name_service/__init__.py
  python/name-service/poetry.lock
  python/name-service/pyproject.toml
  python/year-service/yearservice/yearapp/apps.py
Labels: type: enhancement, type: maintenance
