Repository honeycombio/example-greeting-service, pull requests merged in 2023-05, with the labels that each got.

#579 maint: update go auto instrumentation
  go-auto-instrumented/README.md
  go-auto-instrumented/greetings-instrumented.yaml
Labels: type: maintenance

#605 maint: use arm-friendly jdk docker images
  java/frontend/Dockerfile
  java/message-service/Dockerfile
  java/name-service/Dockerfile
  java/year-service/Dockerfile
Labels: type: maintenance, merge at will

#604 maint: update go auto-instr with published image
  go-auto-instrumented/README.md
  go-auto-instrumented/greetings-instrumented.yaml
Labels: type: maintenance, merge at will

#607 docs: update readme
  README.md
Labels: type: documentation

#608 feat: dockerize dotnet services
  Tiltfile
  docker-compose.dotnet.yml
  dotnet/Tiltfile
Labels: type: enhancement

#612 maint: Update go services with newer go version and newer distro
  golang/frontend/Dockerfile
  golang/go.mod
  golang/go.sum
  golang/message-service/Dockerfile
  golang/name-service/Dockerfile
  golang/year-service/Dockerfile
  golang/year-service/main.go
Labels: type: maintenance, merge at will

#622 feat: dockerize python services
  README.md
  Tiltfile
  docker-compose.python.yml
  python/README.md
  python/frontend/Dockerfile
  python/message-service/Dockerfile
  python/name-service/Dockerfile
  python/year-service/Dockerfile
  python/year-service/yearservice/yearservice/settings.py
Labels: type: enhancement
