Repository honeycombio/example-greeting-service, pull requests merged in 2024-03, with the labels that each got.

#964 maint: Update node year service to use bunyan logging and send OTLP logs
  docker-compose.node.yml
  node/year-service/main.js
  node/year-service/package-lock.json
  node/year-service/package.json
  node/year-service/tracing.js
Labels: type: maintenance

#973 feat: convert python year service to otel, add logs, update deps
  otel-collector-config.yaml
  python/frontend/poetry.lock
  python/frontend/pyproject.toml
  python/message-service/poetry.lock
  python/message-service/pyproject.toml
  python/name-service/poetry.lock
  python/name-service/pyproject.toml
  python/year-service/Dockerfile
  python/year-service/poetry.lock
  python/year-service/pyproject.toml
  python/year-service/yearservice/manage.py
  python/year-service/yearservice/yearapp/apps.py
  python/year-service/yearservice/yearapp/views.py
  python/year-service/yearservice/yearservice/settings.py
Labels: type: enhancement

#972 maint: disable dependabot
  .github/dependabot.yml
Labels: type: maintenance

#974 maint: Revert "maint: disable dependabot"
  .github/dependabot.yml
Labels: type: maintenance

#989 maint: more python dependency updates
  python/frontend/poetry.lock
  python/frontend/pyproject.toml
  python/message-service/poetry.lock
  python/message-service/pyproject.toml
  python/name-service/poetry.lock
  python/name-service/pyproject.toml
  python/year-service/poetry.lock
  python/year-service/pyproject.toml
Labels: type: maintenance

#988 maint: update nodejs dependencies
  node/frontend-service/package-lock.json
  node/frontend-service/package.json
  node/message-service/package-lock.json
  node/message-service/package.json
  node/name-service/package-lock.json
  node/name-service/package.json
  node/year-service/package-lock.json
  node/year-service/package.json
Labels: type: maintenance

#992 maint: Update ubuntu image in workflows to latest
  .github/workflows/publish-ghcr.yml
Labels: type: maintenance, version: no bump

#995 fix: Revert "maint: Update ubuntu image in workflows to latest"
  .github/workflows/publish-ghcr.yml
Labels: type: bug, merge at will

#993 maint: update golang/year service to be plain otel
  Tiltfile
  golang/year-service/main.go
Labels: type: maintenance
